<?php

use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	DB::table('cities')->delete();
    	$city = array(
    		array('name' => 'Adilpur',  'state_id' => 1),
    		array('name' => 'Badah',  'state_id' => 1),
    		array('name' => 'Badin',  'state_id' => 1),
    		array('name' => 'Bagarji',  'state_id' => 1),
    		array('name' => 'Bakshshapur',  'state_id' => 1),
    		array('name' => 'Berani',  'state_id' => 1),
    		array('name' => 'Bhan',  'state_id' => 1),
    		array('name' => 'Bhiria City',  'state_id' => 1),
    		array('name' => 'Bhiria Road',  'state_id' => 1),
    		array('name' => 'Bhit Shah',  'state_id' => 1),
    		array('name' => 'Bozdar',  'state_id' => 1),
    		array('name' => 'Bulri',  'state_id' => 1),
    		array('name' => 'Chak',  'state_id' => 1),
    		array('name' => 'Chohar Jamali',  'state_id' => 1),
    		array('name' => 'Chor',  'state_id' => 1),
    		array('name' => 'Dadu',  'state_id' => 1),
    		array('name' => 'Daharki',  'state_id' => 1),
    		array('name' => 'Daro',  'state_id' => 1),
    		array('name' => 'Darya Khan Mari',  'state_id' => 1),
    		array('name' => 'Daur',  'state_id' => 1),
    		array('name' => 'Dhoronaro',  'state_id' => 1),
    		array('name' => 'Digri',  'state_id' => 1),
    		array('name' => 'Diplo',  'state_id' => 1),
    		array('name' => 'Dokri',  'state_id' => 1),
    		array('name' => 'Faqirabad',  'state_id' => 1),
    		array('name' => 'Gambat',  'state_id' => 1),
    		array('name' => 'Garello',  'state_id' => 1),
    		array('name' => 'Garhi Khairo',  'state_id' => 1),
    		array('name' => 'Garhi Yasin',  'state_id' => 1),
    		array('name' => 'Gharo',  'state_id' => 1),
    		array('name' => 'Ghauspur',  'state_id' => 1),
    		array('name' => 'Ghotki',  'state_id' => 1),
    		array('name' => 'Golarchi',  'state_id' => 1),
    		array('name' => 'Guddu',  'state_id' => 1),
    		array('name' => 'Gulistan-E-Jauhar',  'state_id' => 1),
    		array('name' => 'Hala',  'state_id' => 1),
    		array('name' => 'Hingorja',  'state_id' => 1),
    		array('name' => 'Hyderabad',  'state_id' => 1),
    		array('name' => 'Islamkot',  'state_id' => 1),
    		array('name' => 'Hyderabad',  'state_id' => 1),
    		array('name' => 'Jacobabad',  'state_id' => 1),
    		array('name' => 'Jam Nawaz Ali',  'state_id' => 1),
    		array('name' => 'Jam Sahib',  'state_id' => 1),
    		array('name' => 'Jati',  'state_id' => 1),
    		array('name' => 'Jhol',  'state_id' => 1),
    		array('name' => 'Jhudo',  'state_id' => 1),
    		array('name' => 'Johi',  'state_id' => 1),
    		array('name' => 'Kadhan',  'state_id' => 1),
    		array('name' => 'Kambar',  'state_id' => 1),
    		array('name' => 'Kandhra',  'state_id' => 1),
    		array('name' => 'Kandiari',  'state_id' => 1),
    		array('name' => 'Kandiaro',  'state_id' => 1),
    		array('name' => 'Karachi',  'state_id' => 1),
    		array('name' => 'Karampur',  'state_id' => 1),
    		array('name' => 'Kario Ghanwar',  'state_id' => 1),
    		array('name' => 'Karoondi',  'state_id' => 1),
    		array('name' => 'Kashmor',  'state_id' => 1),
    		array('name' => 'Kazi Ahmad',  'state_id' => 1),
    		array('name' => 'Keti Bandar',  'state_id' => 1),
    		array('name' => 'Khadro',  'state_id' => 1),
    		array('name' => 'Khairpur',  'state_id' => 1),
    		array('name' => 'Khairpur Nathan Shah',  'state_id' => 1),
    		array('name' => 'Khandh Kot',  'state_id' => 1),
    		array('name' => 'Khanpur',  'state_id' => 1),
    		array('name' => 'Khipro',  'state_id' => 1),
    		array('name' => 'Khoski',  'state_id' => 1),
    		array('name' => 'Khuhra',  'state_id' => 1),
    		array('name' => 'Khyber',  'state_id' => 1),
    		array('name' => 'Kot Diji',  'state_id' => 1),
    		array('name' => 'Kot Ghulam Mohammad',  'state_id' => 1),
    		array('name' => 'Kotri',  'state_id' => 1),
    		array('name' => 'Kumb',  'state_id' => 1),
    		array('name' => 'Kunri',  'state_id' => 1),
    		array('name' => 'Lakhi',  'state_id' => 1),
    		array('name' => 'Larkana',  'state_id' => 1),
    		array('name' => 'Madeji',  'state_id' => 1),
    		array('name' => 'Matiari',  'state_id' => 1),
    		array('name' => 'Matli',  'state_id' => 1),
    		array('name' => 'Mehar',  'state_id' => 1),
    		array('name' => 'Mehrabpur',  'state_id' => 1),
    		array('name' => 'Miro Khan',  'state_id' => 1),
    		array('name' => 'Mirpur Bathoro',  'state_id' => 1),
    		array('name' => 'Mirpur Khas',  'state_id' => 1),
    		array('name' => 'Mirpur Mathelo',  'state_id' => 1),
    		array('name' => 'Mirpur Sakro',  'state_id' => 1),
    		array('name' => 'Mirwah',  'state_id' => 1),
    		array('name' => 'Mithi',  'state_id' => 1),
    		array('name' => 'Moro',  'state_id' => 1),
    		array('name' => 'Nabisar',  'state_id' => 1),
    		array('name' => 'Nasarpur',  'state_id' => 1),
    		array('name' => 'Nasirabad',  'state_id' => 1),
    		array('name' => 'Naudero',  'state_id' => 1),
    		array('name' => 'Naukot',  'state_id' => 1),
    		array('name' => 'Naushahro Firoz',  'state_id' => 1),
    		array('name' => 'Nawabshah',  'state_id' => 1),
    		array('name' => 'Oderolal Station',  'state_id' => 1),
    		array('name' => 'Pacca Chang',  'state_id' => 1),
    		array('name' => 'Padidan',  'state_id' => 1),
    		array('name' => 'Pano Aqil',  'state_id' => 1),
    		array('name' => 'Perumal',  'state_id' => 1),
    		array('name' => 'Phulji',  'state_id' => 1),
    		array('name' => 'Pirjo Goth',  'state_id' => 1),
    		array('name' => 'Piryaloi',  'state_id' => 1),
    		array('name' => 'Pithoro',  'state_id' => 1),
    		array('name' => 'Radhan',  'state_id' => 1),
    		array('name' => ' Rajo Khanani ',  'state_id' => 1),
    		array('name' => 'Ranipur',  'state_id' => 1),
    		array('name' => 'Ratodero',  'state_id' => 1),
    		array('name' => 'Rohri',  'state_id' => 1),
    		array('name' => 'Rustam',  'state_id' => 1),
    		array('name' => 'Saeedabad',  'state_id' => 1),
    		array('name' => 'Sakrand',  'state_id' => 1),
    		array('name' => 'Samaro',  'state_id' => 1),
    		array('name' => 'Sanghar',  'state_id' => 1),
    		array('name' => 'Sann',  'state_id' => 1),
    		array('name' => 'Sarhari',  'state_id' => 1),
    		array('name' => 'Sehwan',  'state_id' => 1),
    		array('name' => 'Setharja',  'state_id' => 1),
    		array('name' => 'Shah Dipalli',  'state_id' => 1),
    		array('name' => 'Shahdadkot',  'state_id' => 1),
    		array('name' => 'Shahdadpur',  'state_id' => 1),
    		array('name' => 'Shahpur Chakar',  'state_id' => 1),
    		array('name' => 'Shahpur Jahania',  'state_id' => 1),
    		array('name' => 'Shikarpur',  'state_id' => 1),
    		array('name' => 'Sinjhoro',  'state_id' => 1),
    		array('name' => 'Sita Road',  'state_id' => 1),
    		array('name' => 'Sobhodero',  'state_id' => 1),
    		array('name' => 'Sujawal',  'state_id' => 1),
    		array('name' => 'Sukkur',  'state_id' => 1),
    		array('name' => 'Talhar',  'state_id' => 1),
    		array('name' => 'Tando Adam ',  'state_id' => 1),
    		array('name' => 'Tando Allah Yar',  'state_id' => 1),
    		array('name' => 'Tando Bagho ',  'state_id' => 1),
    		array('name' => 'Tando Ghulam Ali',  'state_id' => 1),
    		array('name' => ' Tando Jam',  'state_id' => 1),
    		array('name' => 'Tando Jan Mohammad',  'state_id' => 1),
    		array('name' => 'Tando Mitha Khan',  'state_id' => 1),
    		array('name' => 'Tando Muhammad Khan',  'state_id' => 1),
    		array('name' => 'Tangwani',  'state_id' => 1),
    		array('name' => 'Thano Bula Khan',  'state_id' => 1),
    		array('name' => 'Thari Mirwah',  'state_id' => 1),
    		array('name' => 'Tharushah ',  'state_id' => 1),
    		array('name' => 'Thatta',  'state_id' => 1),
    		array('name' => 'Ther I',  'state_id' => 1),
    		array('name' => 'Ther I Mohabat',  'state_id' => 1),
    		array('name' => 'Thul',  'state_id' => 1),
    		array('name' => 'Ubauro ',  'state_id' => 1),
    		array('name' => 'Umarkot',  'state_id' => 1),
    		array('name' => 'Warah',  'state_id' => 1)
    	);
DB::table('cities')->insert($city);
}
}
